CREATE TABLE SCHEDULE
(
    id           BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 ID',
    username     VARCHAR(100) NOT NULL COMMENT '사용자 명',
    title        VARCHAR(100) NOT NULL COMMENT '제목',
    content      VARCHAR(100) NOT NULL COMMENT '할일',
    password     VARCHAR(100) NOT NULL COMMENT '비밀번호',
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
)